# Generated by Django 2.0.7 on 2018-07-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
                ('cnpj', models.CharField(max_length=14)),
                ('rua', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
            ],
        ),
    ]
